[book]
authors = ["Project Team"]
language = "en"
src = "src"
title = "IATI Project Location Standard Documentation"

[output.html]
additional-css = ["src/custom.css"]
git-repository-url = "https://github.com/mapme-initiative/IATI-Project-Location-Standard"

[preprocessor.links]
